#!/bin/sh

trap cleanup 0 INT QUIT TERM

cleanup()
{
    if [ -f "/tmp/.X${TTY}-lock" ]; then
        rm -f "/tmp/.X${TTY}-lock"
    fi

    if [ -S "/tmp/.X11-unix/X${TTY}" ]; then
        rm -f "/tmp/.X11-unix/X${TTY}"
    fi
}

export NSS_SSHSOCK_SOCKET="/var/run/ldm_socket_0_server"
export NSS_SSHSOCK_HOST="server"

# Do X settings using the standard LTSP configuration tools
. /usr/share/ltsp/screen-x-common

# There's a bug in lightdm-1.4.0/liblightdm-gobject/session.c
# update_sessions() method which causes it to always use the default
# config dir to load lightdm.conf even if configuration file has been
# set on the command line. To overcome this problem, copy the lightdm.conf
# also to /etc/lightdm/lightdm.conf so that it gets read properly.

cp /usr/share/ltsp-lightdm/lightdm.conf /etc/lightdm/

unset DISPLAY # prevents lightdm from using Xephyr
/usr/sbin/lightdm -c /usr/share/ltsp-lightdm/lightdm.conf --xsessions-dir=/usr/share/ltsp-lightdm/xsessions
