#!/bin/sh

trap cleanup 0 INT QUIT TERM

cleanup()
{
    if [ -f "/tmp/.X${TTY}-lock" ]; then
        rm -f "/tmp/.X${TTY}-lock"
    fi

    if [ -S "/tmp/.X11-unix/X${TTY}" ]; then
        rm -f "/tmp/.X11-unix/X${TTY}"
    fi
}

export NSS_SSHSOCK_SOCKET="/var/run/ldm_socket_0_server"
export NSS_SSHSOCK_HOST="server"

# Do X settings using the standard LTSP configuration tools
. /usr/share/ltsp/screen-x-common

# Link to the ltsp-generated xorg.conf (created above) so that lightdm/X can
# use it.  However, do not overwrite the default /etc/X11/xorg.conf if it
# exists, in case something has created it in some way.
ln -s /var/run/ltsp-xorg.conf /etc/X11/xorg.conf 2>/dev/null

# There's a bug in lightdm-1.4.0/liblightdm-gobject/session.c
# update_sessions() method which causes it to always use the default
# config dir to load lightdm.conf even if configuration file has been
# set on the command line. To overcome this problem, copy the lightdm.conf
# also to /etc/lightdm/lightdm.conf so that it gets read properly.

cp /usr/share/ltsp-lightdm/lightdm.conf /etc/lightdm/

if [ -n "${X_COLOR_DEPTH}" ]; then
  echo "xserver-command=X -depth ${X_COLOR_DEPTH}" >> /etc/lightdm/lightdm.conf
fi

# XXX dbus must be started before lightdm... actually, puavo-client-core
# XXX should wait for dbus to start, but this did not work for some reasons,
# XXX this one works better:
service dbus restart || service dbus start

unset DISPLAY # prevents lightdm from using Xephyr
/usr/sbin/lightdm -c /etc/lightdm/lightdm.conf
