#!/bin/sh

trap cleanup 0 INT QUIT TERM

cleanup()
{
    if [ -f "/tmp/.X${TTY}-lock" ]; then
        rm -f "/tmp/.X${TTY}-lock"
    fi

    if [ -S "/tmp/.X11-unix/X${TTY}" ]; then
        rm -f "/tmp/.X11-unix/X${TTY}"
    fi
}

unset DISPLAY # prevents lightdm from using Xephyr
/usr/sbin/lightdm
