#!/bin/bash
# Copyright © 2012 Opinsys Oy
#
# Based on the example from libpam-sshauth
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

test -n "$PAM_USER" || exit 1
[[ $PAM_USER = "lightdm" ]] && exit 0

export PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
SERVER="server"
SOCKETDIR="/var/run"
#SOCKET="${SOCKETDIR}/ldm_socket_$$_$SERVER"
SOCKET="${SOCKETDIR}/ldm_socket_0_server"
export DISPLAY=${PAM_TTY}
export LDM_USERNAME=$PAM_USER
export LDM_SERVER=$SERVER
export SSH_ASKPASS="/usr/bin/shm_askpass"

export NSS_SSHSOCK_SOCKET="$SOCKET"
export NSS_SSHSOCK_HOST="$SERVER"

test -x $(which daemon) || exit 1


#
# Set XAUTHORITY based on current display manager.
#
setenvxauth() {
    #
    # Use DM's XAUTHORITY
    #
    if [ -z "${XAUTHORITY}" ]; then
        if [ $PAM_SERVICE = "lightdm" ]; then
            export XAUTHORITY="/var/run/lightdm/root/$DISPLAY"

        elif [ $PAM_SERVICE = "gdm" ]; then
            export XAUTHORITY="$(ls -d1 /var/run/gdm/auth-for-gdm*|head -n 1)/database"

        elif [ $PAM_SERVICE = "xdm" ]; then
            export XAUTHORITY="$(ls -1 /var/lib/xdm/authdir/authfiles/*|head -n 1)"

        else
            logger "ltsp-session: unsupported service: $PAM_SERVICE"
            exit 1
        fi
    fi
    logger "ltsp-session: using XAUTHORITY file $XAUTHORITY"
}


#
# Sets necessary environment variables for LDM scripts.
#
setenv() {
    #
    # Load lts.conf
    #
    PROCESS_LTS_CONF=Yes
    . /usr/share/ltsp/ltsp_config
    # NOTE: screen-x-common scripts break login
    #. /usr/share/ltsp/screen-x-common

    setenvxauth

    #
    # Server scalability.  If there exists a /usr/share/ltsp/get_hosts file, then
    # use it to populate the LDM_SERVER environment variable.
    #
    if [ -z "${LDM_SERVER}" ]; then
        if [ -x /usr/share/ltsp/get_hosts ]; then
            LDM_SERVER=$(/usr/share/ltsp/get_hosts)
        else
            # Use hostname to allow IP changes without need for ltsp-update-sshkeys
            LDM_SERVER="server"
        fi
    fi
    export LDM_SERVER

    #
    # Loop though each of the hosts, and get their ldminfo
    #
    if [ -n "${LDM_SERVER}" ]; then
        test ! -d /var/run/ldm && mkdir -p /var/run/ldm
        for SRV in $LDM_SERVER ; do
            # Write server to /etc/hosts so reverse DNS lookup is not necessary
            if ! grep -q "$SRV" /etc/hosts ; then
                echo "$SRV  server-$SRV" >> /etc/hosts
            fi
            # For this to work, ldm-server needs to be installed in the chroot
            if boolean_is_true "$LTSP_FATCLIENT" && [ -x /usr/share/ldm/ldminfod ]; then
                /usr/share/ldm/ldminfod > /var/run/ldm/$SRV
                break
            else
                nc $nc_q_param -w 5 $SRV 9571 > /var/run/ldm/$SRV
            fi
        done
    fi

    #get_xfs_settings "$LDM_SERVER"

    #
    # Define our session
    #
    SESSIONLIST="/etc/X11/xinit/Xsession \
                 /etc/X11/Xsession \
                 /usr/lib/X11/xdm/Xsession \
                 /etc/X11/xdm/Xsession"
    if [ -z "${LDM_XSESSION}" ]; then        # If admin hasn't specified session
        for SESSION in ${SESSIONLIST}; do
            if [ -x ${SESSION} ]; then
                export LDM_DEFAULT_XSESSION=${SESSION}
                break
            fi
        done
    fi

    export LDM_XSESSION=$LDM_DEFAULT_XSESSION
    #export LDM_LANGUAGE
    #export LDM_SELECTED_SESSION

    #
    # Set X properties by calling appropriate xinitrc.d scripts.
    # Required for LTSPFS.
    #
    if [ -x /usr/share/ltsp/xinitrc ]; then
        /usr/share/ltsp/xinitrc
    fi
}


#
# Wait for our socket to appear.
#
waitfor () {
    S=$1

    while [ ! -S "${S}" ]; do
        logger "ltsp-session: waiting for socket $S"
        sleep 1
    done
}


#
# Open ssh control socket.
#
# The "daemon" utility backgrounds any script or command, and
# detaches from the controlling terminal.
# With no controlling terminal, and $DISPLAY set, ssh will use
# "shm_askpass" specified in SSH_ASKPASS to obtain the password.
#
open_socket () {
    S=$1

    if [ -n "${DISPLAY}" ]; then
        daemon -i -- ssh -q -N -Y -M -K -S "${S}" -l ${PAM_USER_REAL} ${SERVER}

        waitfor "${S}"

        logger "ltsp-session: socket $S open"
    fi
}


#
# Close ssh control socket.
#
close_socket () {
    S=$1
    ssh -q -S "$S" -O exit ${SERVER}
}


#
# This is a session helper script to be used in conjunction with pam_exec.
#
case ${PAM_TYPE} in

auth)

    logger "ltsp-session: start auth"

    # Set XAUTHORITY. Required here for LDM_DIRECTX.
    setenvxauth

    #
    # Construct our socket directory.
    #
    if [ ! -d "${SOCKETDIR}" ]; then
        mkdir -p "${SOCKETDIR}"
    fi

    #
    # We're authenticating, so we'll store the auth token using shm_askpass
    # shm_askpass --write will read a password from stdin, and store it in
    # POSIX shared memory.
    #

    # This is a hack to work around shm_askpass problem that requires
    # that the user defined in PAM_USER exists. By setting it to
    # something else (e.g. root or lightdm) while using shm_askpass we
    # can work around the problem. A real fix is needed for this.
    # open_socket() is also patched to use PAM_USER_REAL.
    export PAM_USER_REAL="${PAM_USER}"
    export PAM_USER="root"

    shm_askpass >/dev/null
    if [ $? -eq 0 ]; then
        shm_askpass --delete
    fi
    shm_askpass --write

    # Socket needs to be openened in auth phase for nss-sshsock to work
    # when lightdm checks that the user account really works
    open_socket "${SOCKET}"
    export LDM_SOCKET=${SOCKET}
    export PAM_USER="${PAM_USER_REAL}"

    # This should be moved to somewhere else,
    # Mount the user home directory through sshfs so that it is available
    # when lightdm tries to write .dmrc and .xsession-errors files under
    # it. NFSv4+kerberos and other mount types should also be supported
    # either through explicit mount commands or through automount.
    logger "ltsp-session: request user data via libnss-sshsock..."

    export LDM_HOME=$(getent passwd ${PAM_USER}|awk -F: '{print $6};')
    export PAM_USER_UID=$(getent passwd ${PAM_USER}|awk -F: '{print $3};')
    export PAM_USER_GID=$(getent passwd ${PAM_USER}|awk -F: '{print $4};')

    if [ -z $PAM_USER_UID ]; then
        logger "ltsp-session: could not get data for user $PAM_USER, aborting"
        exit 1
    fi
    logger "ltsp-session: user $PAM_USER, uid $PAM_USER_UID, gid $PAM_USER_GID"

    mkdir -m 0700 -p "${LDM_HOME}"
    chown ${PAM_USER_UID}.${PAM_USER_GID} "${LDM_HOME}"

    logger "ltsp-session: mounting user home directory ($LDM_HOME) with sshfs"
    export SSHFS_HOME=true
    sshfs -o ${follow_home_symlinks}allow_other,ControlPath=${LDM_SOCKET} ${LDM_SERVER}:${LDM_HOME} ${LDM_HOME}

    ;;


open_session)

    #
    # Open user session.
    # The control socket is first spawn, then the session is launched
    # using the same socket.
    #

    logger "ltsp-session: open session"

    setenv

    if boolean_is_true "$LTSP_FATCLIENT"; then
        logger "ltsp-session: fat clients are not supported sorry :("

    else
        logger "ltsp-session: run pressh scripts"
        /usr/share/ldm/ldm-script pressh

#        open_socket "${SOCKET}"
        export LDM_SOCKET=${SOCKET}
        # get the IP address via the ssh tunnel
        export LDMINFO_IPADDR=$(
            ssh -S ${LDM_SOCKET} $LDM_SERVER 'echo $SSH_CLIENT'|cut -d' ' -f1)

        test -n "$LDM_SERVER" || exit 1
        test -n "$LDM_SOCKET" || exit 1

        logger "ltsp-session: start thin client"

        /usr/share/ldm/ldm-script start
        daemon -i -- /usr/share/ldm/ldm-script xsession
    fi

    ;;


close_session)

    #
    # We're closing the session down, so cause the socket to exit.
    # Libnss-sshsock needs to finalise before closing the socket.
    #
    logger "ltsp-session: close session"
    sleep 1
    close_socket "${SOCKET}"

    ;;

esac

# print environment variables to debug file
[[ -n $ENV_DEBUG ]] && env > $ENV_DEBUG

exit 0
