#!/bin/bash
# Copyright © 2012 Opinsys Oy
#
# Based on the example from libpam-sshauth
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

test -n "$PAM_USER" || exit 1
[[ $PAM_USER = "lightdm" ]] && exit 0

export PATH=/bin:/usr/bin:/sbin:/usr/sbin
SERVER="server"
SOCKETDIR="/var/run"
SOCKET="${SOCKETDIR}/ldm_socket_$$_$SERVER"
export DISPLAY=${PAM_TTY}
export LDM_USERNAME=$PAM_USER
export SSH_ASKPASS="/usr/bin/shm_askpass"

test -x $(which daemon) || exit 1


#
# setenv
# Sets necessary environment variables.
#
setenv() {
    #
    # Load lts.conf
    #
    PROCESS_LTS_CONF=Yes
    . /usr/share/ltsp/ltsp_config
    # NOTE: screen-x-common scripts break login
    #. /usr/share/ltsp/screen-x-common

    #
    # Use DM's XAUTHORITY
    #
    if [ -z "${XAUTHORITY}" ]; then
        if [ $PAM_SERVICE = "lightdm" ]; then
            export XAUTHORITY="/var/run/lightdm/root/$DISPLAY"

        elif [ $PAM_SERVICE = "gdm" ]; then
            export XAUTHORITY="$(ls -d1 /var/run/gdm/auth-for-gdm*|head -n 1)/database"

        elif [ $PAM_SERVICE = "xdm" ]; then
            export XAUTHORITY="$(ls -1 /var/lib/xdm/authdir/authfiles/*|head -n 1)"

        else
            logger "ltsp-session: unsupported service: $PAM_SERVICE"
            exit 1
        fi
    fi
    logger "ltsp-session: using XAUTHORITY file $XAUTHORITY"

    #
    # Server scalability.  If there exists a /usr/share/ltsp/get_hosts file, then
    # use it to populate the LDM_SERVER environment variable.
    #
    if [ -z "${LDM_SERVER}" ]; then
        if [ -x /usr/share/ltsp/get_hosts ]; then
            LDM_SERVER=$(/usr/share/ltsp/get_hosts)
        else
            # Use hostname to allow IP changes without need for ltsp-update-sshkeys
            LDM_SERVER="server"
        fi
    fi
    export LDM_SERVER

    #
    # Loop though each of the hosts, and get their ldminfo
    #
    if [ -n "${LDM_SERVER}" ]; then
        test ! -d /var/run/ldm && mkdir -p /var/run/ldm
        for SRV in $LDM_SERVER ; do
            # Write server to /etc/hosts so reverse DNS lookup is not necessary
            if ! grep -q "$SRV" /etc/hosts ; then
                echo "$SRV  server-$SRV" >> /etc/hosts
            fi
            # For this to work, ldm-server needs to be installed in the chroot
            if boolean_is_true "$LTSP_FATCLIENT" && [ -x /usr/share/ldm/ldminfod ]; then
                /usr/share/ldm/ldminfod > /var/run/ldm/$SRV
                break
            else
                nc $nc_q_param -w 5 $SRV 9571 > /var/run/ldm/$SRV
            fi
        done
    fi

    #get_xfs_settings "$LDM_SERVER"

    #
    # Define our session
    #
    SESSIONLIST="/etc/X11/xinit/Xsession \
                 /etc/X11/Xsession \
                 /usr/lib/X11/xdm/Xsession \
                 /etc/X11/xdm/Xsession"
    if [ -z "${LDM_XSESSION}" ]; then        # If admin hasn't specified session
        for SESSION in ${SESSIONLIST}; do
            if [ -x ${SESSION} ]; then
                export LDM_DEFAULT_XSESSION=${SESSION}
                break
            fi
        done
    fi

    export LDM_XSESSION=$LDM_DEFAULT_XSESSION
    #export LDM_LANGUAGE
    #export LDM_SELECTED_SESSION

    #
    # Set X properties by calling appropriate xinitrc.d scripts
    #
    if [ -x /usr/share/ltsp/xinitrc ]; then
        /usr/share/ltsp/xinitrc
    fi
}


#
# waitfor
#
# Wait for our socket to appear.
#
waitfor () {
    S=$1

    while [ ! -S "${S}" ]; do
        logger "ltsp-session: waiting for socket"
        sleep 1
    done
}


open_socket () {
    S=$1

    if [ -n "${DISPLAY}" ]; then
        #
        # We have a $DISPLAY variable set.  Spawn an ssh session.
        # Note, you must install the "daemon" package to obtain the "daemon"
        # utility.  This nice little program easily backgrounds any script or
        # command, and has the added advantage (for us) of disassociating from
        # the controlling terminal.  With no controlling terminal, and $DISPLAY
        # set, ssh will use the program specified in SSH_ASKPASS to obtain the
        # passowrd.  Since this was stored in the "auth" phase above,
        # shm_askpass will pass it to ssh for it to authenticate with.
        #
        daemon -i -- ssh -q -N -Y -M -K -S "${S}" -l ${PAM_USER} ${SERVER}

        #
        # Wait for the socket to actually become available before returning.
        #
        waitfor "${S}"

        logger "ltsp-session: socket $S open"
    fi
}


close_socket () {
    S=$1
    ssh -q -S "$S" -O exit ${SERVER}
}


#
# This is an example session helper script to be used in conjunction with
# pam_exec and libpam_sshauth.
#
case ${PAM_TYPE} in

auth)

    logger "ltsp-session: start auth"

    #
    # Construct our socket directory.
    #
    if [ ! -d "${SOCKETDIR}" ]; then
        mkdir -p "${SOCKETDIR}"
    fi

    #
    # We're authenticating, so we'll store the auth token using shm_askpass
    # shm_askpass --write will read a password from stdin, and store it in
    # POSIX shared memory.
    #
    shm_askpass >/dev/null
    if [ $? -eq 0 ]; then
        shm_askpass --delete
    fi
    shm_askpass --write

    ;;


open_session)

    #
    # Open user session.
    # The control socket is first spawn, then the session is launched
    # using the same socket.
    #

    logger "ltsp-session: open session"

    setenv

    if boolean_is_true "$LTSP_FATCLIENT"; then
        logger "ltsp-session: fat clients are not supported sorry :("

    else
        logger "ltsp-session: run pressh scripts"
        /usr/share/ldm/ldm-script pressh

        open_socket "${SOCKET}"
        export LDM_SOCKET=${SOCKET}
        # get the IP address via the ssh tunnel
        export LDMINFO_IPADDR=$(
            ssh -S ${LDM_SOCKET} $LDM_SERVER 'echo $SSH_CLIENT'|cut -d' ' -f1)

        test -n "$LDM_SERVER" || exit 1
        test -n "$LDM_SOCKET" || exit 1

        logger "ltsp-session: start thin client"

        /usr/share/ldm/ldm-script start
        daemon -i -- /usr/share/ldm/ldm-script xsession
    fi

    ;;


close_session)

    #
    # We're closing the session down, so cause the socket to exit.
    #
    logger "ltsp-session: close session"
    close_socket "${SOCKET}"

    ;;

esac

exit 0
